sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eyRe+yiOB63CSGWDrsgvhSlNVDWaodao0o5+huh0wRFaeXngl+Ui5dDl25xFHuGl8/rPFLkovIvPgRlLiv6RYlRlQ9n2jBNUVJc/Xddh1xprMJExl3+pil/iEuww+XREgmqIyNSR1ybN2Kv5/fDdRAjQPM1dvyICbdyeKPVUAz0aR9epSNC4IeWkd3Yss6BSxjmmxg8Q1DOoWvqoNVKhiZxEEoZ6cgiFK0183BPtLHQ3psWWIPa45O4FNG3xXYIk01kIHLIXNk2++Qubsgag65E3ZLTtj6kD8lT4YMHD+3lprLA06T2xZuzrsB+2sLm/yysKoiqEI4PI406pN6UpBTZrTS9AigJhJCdmMY1zN8CefyMDna0BMuNy2P7Z6IlOiyO6+dP6zgudFF3eJ4rFSWyJ7mey4/akaHOBzhazD5RnDh2+9tNpCvAJVXyi2KJANS1rhrIUXQ9dqCYyB1CC8DT+7yuaASdHaO1xnBeiKlhVGsQWXSPC6XYC5RZDdupiaxqYRj3Tu17oiFqMDromQNwjlh8zrPoFTizqNy8Q245gZBPrBipf4GjycZQ2jI/l8YBzDJy41W69reQ+hlnvS+cRUyp3ixcxexvQjFpyhSjpVoocqP2S3y8ZEtZBRtWqeSHr6wgRrnzKfltW4VtgdPWjuY3ex6aETa2yVmQN1/0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wild-Flowers-An-Aid-to-Knowledge-of-Our-Wild-Flowers-and-Their-Insect-Visitors_3003
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy